/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/isometric_room/scene.gltf -K -k 
Author: JamesBryan21 (https://sketchfab.com/JamesBryan21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-room-25f72004e9fa441ca420fadf58798976
Title: Isometric Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
          <group name="c24acbf02bb247dc994de245f9be726afbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Light" position={[-34.274, 1043.585, -41.714]} rotation={[1.89, 0.881, -2.045]} scale={100}>
                <group name="Object_4" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_5" />
                </group>
              </group>
              <group name="Camera" position={[1207.918, 1395.117, 959.666]} rotation={[Math.PI, 0.756, 2.68]} scale={100}>
                <group name="Object_7" />
              </group>
              <group name="Plane" rotation={[-Math.PI / 2, 0, 0]} scale={594.89}>
                <mesh name="Plane_Ground_0" geometry={nodes.Plane_Ground_0.geometry} material={materials.Ground} />
              </group>
              <group name="Table" position={[350.483, 218.784, -501.122]} rotation={[-Math.PI / 2, 0, 0]} scale={[241.235, 100, 13.886]}>
                <mesh name="Table_Desk_0" geometry={nodes.Table_Desk_0.geometry} material={materials.Desk} />
              </group>
              <group name="Pc_monitor" position={[2.037, 325.814, -482.949]} rotation={[-Math.PI / 2, 0, 0.989]} scale={[61.099, 54.358, 54.358]}>
                <mesh name="Pc_monitor_Pc_monitor_0" geometry={nodes.Pc_monitor_Pc_monitor_0.geometry} material={materials.Pc_monitor} />
              </group>
              <group name="Book_shelf" position={[110.493, 625.383, -589.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[11.107, 10.525, 100]}>
                <mesh name="Book_shelf_BookShelf_0" geometry={nodes.Book_shelf_BookShelf_0.geometry} material={materials.BookShelf} />
              </group>
              <group name="PC_Old" position={[5.977, 252.237, -491.407]} rotation={[-Math.PI / 2, 0, 0.909]} scale={[69.413, 53.793, 20.382]}>
                <mesh name="PC_Old_pC_0" geometry={nodes.PC_Old_pC_0.geometry} material={materials.material} />
              </group>
              <group name="Books" position={[182.214, 530.205, -572.589]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.932, 22.459, 29.888]}>
                <mesh name="Books_Material004_0" geometry={nodes.Books_Material004_0.geometry} material={materials.material_0} />
              </group>
              <group name="Floppy_disc" position={[46.8, 218.216, -386.359]} rotation={[Math.PI / 2, 0, 0]} scale={[-15.152, 15.152, 0.812]}>
                <mesh name="Floppy_disc_Floppy_discs_0" geometry={nodes.Floppy_disc_Floppy_discs_0.geometry} material={materials.Floppy_discs} />
              </group>
              <group name="Keyboard" position={[217.078, 233.417, -425.964]} rotation={[Math.PI / 2, 0, 0]} scale={[-76.001, 22.998, 1.289]}>
                <group name="keys_text" position={[0.63, 0.166, -4.115]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]}>
                  <mesh name="keys_text_Keyboard_text_0" geometry={nodes.keys_text_Keyboard_text_0.geometry} material={materials.Keyboard_text} />
                </group>
                <group name="Keys2_keyboard" position={[0.521, 0.428, -3.295]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]}>
                  <mesh name="Keys2_keyboard_black_keys2_0" geometry={nodes.Keys2_keyboard_black_keys2_0.geometry} material={materials.black_keys2} />
                </group>
                <group name="Keys_keyboard" position={[0.632, 0.698, -3.295]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]}>
                  <mesh name="Keys_keyboard_black_keys_3_0" geometry={nodes.Keys_keyboard_black_keys_3_0.geometry} material={materials.black_keys_3} />
                </group>
                <group name="Keys3_keyboard" position={[0.527, -0.156, -5.617]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]}>
                  <mesh name="Keys3_keyboard_black_keys_0" geometry={nodes.Keys3_keyboard_black_keys_0.geometry} material={materials.black_keys} />
                </group>
                <mesh name="Keyboard_Material003_0" geometry={nodes.Keyboard_Material003_0.geometry} material={materials['Material.003']} />
              </group>
              <group name="Door" position={[-594.287, 103.127, -242.226]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.271, 146.196, 88.558]}>
                <mesh name="Door_DOOR_0" geometry={nodes.Door_DOOR_0.geometry} material={materials.DOOR} />
              </group>
              <group name="Window" position={[-593.26, 706.104, -369.916]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.639, 27.391, 62.489]}>
                <mesh name="Window_window_0" geometry={nodes.Window_window_0.geometry} material={materials.window} />
              </group>
              <group name="Light_switch" position={[-199.999, 881.453, -591.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.851, 6.851, 299.215]}>
                <mesh name="Light_switch_switch_0" geometry={nodes.Light_switch_switch_0.geometry} material={materials['switch']} />
              </group>
              <group name="Shelf" position={[-511.672, 237.388, 303.33]} rotation={[-Math.PI / 2, 0, 0]} scale={[7.275, 9.263, 11.598]}>
                <mesh name="Shelf_SHELF_0" geometry={nodes.Shelf_SHELF_0.geometry} material={materials.SHELF} />
              </group>
              <group name="Cube" position={[-187.773, 142.36, -597.781]} rotation={[-Math.PI / 2, 0, 0]} scale={[19.005, 0.748, 11.254]}>
                <mesh name="Cube__0" geometry={nodes.Cube__0.geometry} material={materials.Cube__0} />
              </group>
              <group name="Cylinder001" position={[-68.881, 251.191, -480.168]} rotation={[0.213, 0.839, -1.73]} scale={3.842}>
                <mesh name="Cylinder001_wires_0" geometry={nodes.Cylinder001_wires_0.geometry} material={materials.wires} />
                <mesh name="Cylinder001_wires_0_1" geometry={nodes.Cylinder001_wires_0_1.geometry} material={materials.wires} />
              </group>
              <group name="Sphere" position={[-453.108, 205.151, 246.751]} rotation={[0, 0.646, 0]} scale={[2.913, 2.913, 4.912]}>
                <mesh name="Sphere_redpill_0" geometry={nodes.Sphere_redpill_0.geometry} material={materials.redpill} />
              </group>
              <group name="Sphere001" position={[-450.611, 205.151, 225.278]} rotation={[0, -0.859, 0]} scale={[2.913, 2.913, 4.912]}>
                <mesh name="Sphere001_bluepill_0" geometry={nodes.Sphere001_bluepill_0.geometry} material={materials.bluepill} />
              </group>
              <group name="Cube001" position={[4.921, 129.736, 508.662]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.788, 10.788, 141.739]}>
                <mesh name="Cube001_Bed_frame_0" geometry={nodes.Cube001_Bed_frame_0.geometry} material={materials.Bed_frame} />
              </group>
              <group name="Cube002" position={[273.276, 111.847, 391.511]} rotation={[-Math.PI / 2, 0, 0]} scale={[260.966, 113.528, 21.78]}>
                <mesh name="Cube002_Matress_0" geometry={nodes.Cube002_Matress_0.geometry} material={materials.Matress} />
              </group>
              <group name="Plane001" position={[220.054, 217.749, 400.541]} rotation={[-Math.PI / 2, -0.199, 0]} scale={[195.208, 142.378, 100]}>
                <mesh name="Plane001_Sheet_0" geometry={nodes.Plane001_Sheet_0.geometry} material={materials.Sheet} />
              </group>
              <group name="Cube003" position={[462.229, 162.104, 413.424]} rotation={[-1.682, -0.216, -0.617]} scale={[35.404, 64.629, 16.017]}>
                <mesh name="Cube003_Pillow_0" geometry={nodes.Cube003_Pillow_0.geometry} material={materials.Pillow} />
              </group>
              <group name="Circle" position={[-451.262, 320.709, 184.904]} rotation={[-Math.PI / 2, 0, 0]} scale={4.508}>
                <mesh name="Circle_ring__0" geometry={nodes.Circle_ring__0.geometry} material={materials.ring} />
              </group>
              <group name="Cube004" position={[-530.073, 37.179, 102.914]} rotation={[-Math.PI / 2, 0, 0]} scale={[63.2, 10.739, 46.269]}>
                <mesh name="Cube004_Briefcase_0" geometry={nodes.Cube004_Briefcase_0.geometry} material={materials.Briefcase} />
              </group>
              <group name="Cylinder" position={[-489.555, 218.393, 372.45]} rotation={[-Math.PI / 2, 0, 0]} scale={16.435}>
                <mesh name="Cylinder_pot_0" geometry={nodes.Cylinder_pot_0.geometry} material={materials.material_26} />
              </group>
              <group name="Cube005" position={[-497.125, 335.604, 292.126]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.245, 24.796, 15.434]}>
                <mesh name="Cube005_camera_0" geometry={nodes.Cube005_camera_0.geometry} material={materials.camera} />
              </group>
              <group name="Circle001" position={[232.473, 241.274, -470.069]} rotation={[0, 1.275, 0]} scale={8.308}>
                <mesh name="Circle001_Glasses_0" geometry={nodes.Circle001_Glasses_0.geometry} material={materials.Glasses} />
              </group>
              <group name="Cylinder002" position={[229.445, 77.185, -284.528]} rotation={[-Math.PI / 2, 0, 0.954]} scale={[10.47, 10.47, 72.067]}>
                <mesh name="Cylinder002_chair_0" geometry={nodes.Cylinder002_chair_0.geometry} material={materials.chair} />
              </group>
              <group name="Cylinder003" position={[-520.528, 1065.639, 551.621]} scale={35.131}>
                <mesh name="Cylinder003_vent_0" geometry={nodes.Cylinder003_vent_0.geometry} material={materials.vent} />
              </group>
              <group name="Plane002" position={[-597.977, 759.094, 377.236]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[178.483, 107.894, 100]}>
                <mesh name="Plane002_Poster_0" geometry={nodes.Plane002_Poster_0.geometry} material={materials.Poster} />
              </group>
              <group name="Sphere002" position={[387.295, 232.939, -520.726]} rotation={[-Math.PI / 2, 0, -1.984]} scale={[33.395, 33.395, 14.392]}>
                <mesh name="Sphere002_Lamp_0" geometry={nodes.Sphere002_Lamp_0.geometry} material={materials.Lamp} />
              </group>
              <group name="Spot" position={[370.674, 365.047, -488.431]} rotation={[-0.843, -0.134, -0.76]} scale={100}>
                <group name="Object_76" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_77" />
                </group>
              </group>
              <group name="Cylinder004" position={[-35.614, 1100.157, -15.702]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.585, 8.585, 53.595]}>
                <mesh name="Cylinder004_light_0" geometry={nodes.Cylinder004_light_0.geometry} material={materials.light} />
              </group>
              <group name="Cube006" position={[-602.954, 927.794, 479.59]} rotation={[-Math.PI / 2, 1.155, 0]} scale={4.668}>
                <mesh name="Cube006_Nail_0" geometry={nodes.Cube006_Nail_0.geometry} material={materials.Nail} />
              </group>
              <group name="PC_Old004" position={[-7.319, 103.241, -365.772]} rotation={[-Math.PI / 2, 0, 0.049]} scale={[69.413, 53.793, 20.382]}>
                <mesh name="PC_Old004_pC_0" geometry={nodes.PC_Old004_pC_0.geometry} material={materials.material} />
              </group>
              <group name="Plane003" position={[564.945, 245.047, 221.385]} rotation={[-Math.PI / 2, 0, -2.006]} scale={[100, 63.422, 100]}>
                <mesh name="Plane003_tshirt_0" geometry={nodes.Plane003_tshirt_0.geometry} material={materials.tshirt} />
              </group>
              <group name="Window001" position={[-593.26, 706.104, -369.916]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.639, 27.391, 62.489]}>
                <mesh name="Window001_window_glow_0" geometry={nodes.Window001_window_glow_0.geometry} material={materials.window_glow} />
              </group>
              <group name="Spot001" position={[-598.173, 691.124, -243.904]} rotation={[0, 0, 1.537]} scale={100}>
                <group name="Object_89" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_90" />
                </group>
              </group>
              <group name="Cylinder005" position={[-35.614, 1100.157, -25.086]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.585, 8.585, 53.595]}>
                <mesh name="Cylinder005_light_0" geometry={nodes.Cylinder005_light_0.geometry} material={materials.light} />
              </group>
              <group name="Plane004" position={[515.237, 232.67, -500.795]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.53, 40.328, 40.328]}>
                <mesh name="Plane004_paper_0" geometry={nodes.Plane004_paper_0.geometry} material={materials.paper} />
              </group>
              <group name="Point" position={[-447.238, 335.921, 194.841]} scale={100}>
                <group name="Object_96" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Object_97" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
