/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/isometric_room/scene.gltf 
Author: JamesBryan21 (https://sketchfab.com/JamesBryan21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-room-25f72004e9fa441ca420fadf58798976
Title: Isometric Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from "framer-motion-3d";

export function Office(props) {
  const {section} = props;
  const { nodes, materials } = useGLTF('/models/isometric_room/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[107.078, 229.417, -365.64]} rotation={[Math.PI / 2, 0, -1.5]} scale={[-76.001, 22.998, 1.289]}>
            <mesh geometry={nodes.Keyboard_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.keys_text_Keyboard_text_0.geometry} material={materials.Keyboard_text} position={[0.63, 0.166, -4.115]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]} />
            <mesh geometry={nodes.Keys2_keyboard_black_keys2_0.geometry} material={materials.black_keys2} position={[0.521, 0.428, -3.295]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]} />
            <mesh geometry={nodes.Keys_keyboard_black_keys_3_0.geometry} material={materials.black_keys_3} position={[0.632, 0.698, -3.295]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]} />
            <mesh geometry={nodes.Keys3_keyboard_black_keys_0.geometry} material={materials.black_keys} position={[0.527, -0.156, -5.617]} rotation={[-Math.PI, 0, 0]} scale={[-0.034, 0.113, 2.016]} />
          </group>
          <motion.group
            scale={[ 0, 0, 0 ]}
            animate = {{
              scale:section === 0 ? 1 : 0.5,
            }}
       position={[-68.881, 251.191, -480.168]} rotation={[0.213, 0.839, -1.73]}>
            <mesh geometry={nodes.Cylinder001_wires_0.geometry} material={materials.wires} />
            <mesh geometry={nodes.Cylinder001_wires_0_1.geometry} material={materials.wires} />
          </motion.group>
          <mesh geometry={nodes.Plane_Ground_0.geometry} material={materials.Ground} rotation={[-Math.PI / 2, 0, 0]} scale={594.89} />
          <mesh geometry={nodes.Table_Desk_0.geometry} material={materials.Desk} position={[350.483, 218.784, -501.122]} rotation={[-Math.PI / 2, 0, 0]} scale={[241.235, 100, 13.886]} />
          <mesh geometry={nodes.Pc_monitor_Pc_monitor_0.geometry} material={materials.Pc_monitor} position={[2.037, 325.814, -482.949]} rotation={[-Math.PI / 2, 0, 0.989]} scale={[61.099, 54.358, 54.358]} />
          <mesh geometry={nodes.Book_shelf_BookShelf_0.geometry} material={materials.BookShelf} position={[110.493, 625.383, -589.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[11.107, 10.525, 100]} />
          <mesh geometry={nodes.PC_Old_pC_0.geometry} material={materials.material} position={[5.977, 252.237, -491.407]} rotation={[-Math.PI / 2, 0, 0.909]} scale={[69.413, 53.793, 20.382]} />
          <mesh geometry={nodes.Books_Material004_0.geometry} material={materials.material_0} position={[182.214, 530.205, -572.589]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.932, 22.459, 29.888]} />
          <mesh geometry={nodes.Floppy_disc_Floppy_discs_0.geometry} material={materials.Floppy_discs} position={[46.8, 218.216, -386.359]} rotation={[Math.PI / 2, 0, 0]} scale={[-15.152, 15.152, 0.812]} />
          <mesh geometry={nodes.Door_DOOR_0.geometry} material={materials.DOOR} position={[-594.287, 103.127, -242.226]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.271, 146.196, 88.558]} />
          <mesh geometry={nodes.Window_window_0.geometry} material={materials.window} position={[-593.26, 706.104, -369.916]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.639, 27.391, 62.489]} />
          <mesh geometry={nodes.Light_switch_switch_0.geometry} material={materials['switch']} position={[-199.999, 881.453, -591.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.851, 6.851, 299.215]} />
          <mesh geometry={nodes.Shelf_SHELF_0.geometry} material={materials.SHELF} position={[-511.672, 237.388, 303.33]} rotation={[-Math.PI / 2, 0, 0]} scale={[7.275, 9.263, 11.598]} />
          <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube__0} position={[-187.773, 142.36, -597.781]} rotation={[-Math.PI / 2, 0, 0]} scale={[19.005, 0.748, 11.254]} />
          <mesh geometry={nodes.Sphere_redpill_0.geometry} material={materials.redpill} position={[-453.108, 205.151, 246.751]} rotation={[0, 0.646, 0]} scale={[2.913, 2.913, 4.912]} />
          <mesh geometry={nodes.Sphere001_bluepill_0.geometry} material={materials.bluepill} position={[-450.611, 205.151, 225.278]} rotation={[0, -0.859, 0]} scale={[2.913, 2.913, 4.912]} />
          <mesh geometry={nodes.Cube001_Bed_frame_0.geometry} material={materials.Bed_frame} position={[4.921, 129.736, 508.662]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.788, 10.788, 141.739]} />
          <mesh geometry={nodes.Cube002_Matress_0.geometry} material={materials.Matress} position={[273.276, 111.847, 391.511]} rotation={[-Math.PI / 2, 0, 0]} scale={[260.966, 113.528, 21.78]} />
          <mesh geometry={nodes.Plane001_Sheet_0.geometry} material={materials.Sheet} position={[220.054, 217.749, 400.541]} rotation={[-Math.PI / 2, -0.199, 0]} scale={[195.208, 142.378, 100]} />
          <mesh geometry={nodes.Cube003_Pillow_0.geometry} material={materials.Pillow} position={[462.229, 162.104, 413.424]} rotation={[-1.682, -0.216, -0.617]} scale={[35.404, 64.629, 16.017]} />
          <mesh geometry={nodes.Circle_ring__0.geometry} material={materials.ring} position={[-451.262, 320.709, 184.904]} rotation={[-Math.PI / 2, 0, 0]} scale={4.508} />
          <mesh geometry={nodes.Cube004_Briefcase_0.geometry} material={materials.Briefcase} position={[-530.073, 37.179, 102.914]} rotation={[-Math.PI / 2, 0, 0]} scale={[63.2, 10.739, 46.269]} />
          <mesh geometry={nodes.Cylinder_pot_0.geometry} material={materials.material_26} position={[-489.555, 218.393, 372.45]} rotation={[-Math.PI / 2, 0, 0]} scale={16.435} />
          <mesh geometry={nodes.Cube005_camera_0.geometry} material={materials.camera} position={[-497.125, 335.604, 292.126]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.245, 24.796, 15.434]} />
          <mesh geometry={nodes.Circle001_Glasses_0.geometry} material={materials.Glasses} position={[232.473, 241.274, -470.069]} rotation={[0, 1.275, 0]} scale={8.308} />
          <mesh geometry={nodes.Cylinder002_chair_0.geometry} material={materials.chair} position={[229.445, 77.185, -308.528]} rotation={[-Math.PI / 2, 0, 0.954]} scale={[10.47, 10.47, 72.067]} />
          <mesh geometry={nodes.Cylinder003_vent_0.geometry} material={materials.vent} position={[-520.528, 1065.639, 551.621]} scale={35.131} />
          <mesh geometry={nodes.Plane002_Poster_0.geometry} material={materials.Poster} position={[-597.977, 759.094, 377.236]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[178.483, 107.894, 100]} />
          <mesh geometry={nodes.Sphere002_Lamp_0.geometry} material={materials.Lamp} position={[387.295, 232.939, -520.726]} rotation={[-Math.PI / 2, 0, -1.984]} scale={[33.395, 33.395, 14.392]} />
          <mesh geometry={nodes.Cylinder004_light_0.geometry} material={materials.light} position={[-35.614, 1100.157, -15.702]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.585, 8.585, 53.595]} />
          <mesh geometry={nodes.Cube006_Nail_0.geometry} material={materials.Nail} position={[-602.954, 927.794, 479.59]} rotation={[-Math.PI / 2, 1.155, 0]} scale={4.668} />
          <mesh geometry={nodes.PC_Old004_pC_0.geometry} material={materials.material} position={[-7.319, 103.241, -365.772]} rotation={[-Math.PI / 2, 0, 0.049]} scale={[69.413, 53.793, 20.382]} />
          <mesh geometry={nodes.Plane003_tshirt_0.geometry} material={materials.tshirt} position={[564.945, 245.047, 221.385]} rotation={[-Math.PI / 2, 0, -2.006]} scale={[100, 63.422, 100]} />
          <mesh geometry={nodes.Window001_window_glow_0.geometry} material={materials.window_glow} position={[-593.26, 706.104, -369.916]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.639, 27.391, 62.489]} />
          <mesh geometry={nodes.Cylinder005_light_0.geometry} material={materials.light} position={[-35.614, 1100.157, -25.086]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.585, 8.585, 53.595]} />
          <mesh geometry={nodes.Plane004_paper_0.geometry} material={materials.paper} position={[515.237, 232.67, -500.795]} rotation={[-Math.PI / 2, 0, 0]} scale={[25.53, 40.328, 40.328]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/isometric_room/scene.gltf')
